alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
ingress:
  rules:
  - component:
      name: lst-api
    match:
      path:
        prefix: /
name: seal-app
region: syd
services:
- dockerfile_path: src/Lst.Api/Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: nth-commit/lst-api
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: lst-api
  source_dir: src/Lst.Api/
